services:
  api:
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - 4000:4000
  web:
    build:
      context: web
      dockerfile: Dockerfile
    ports:
      - 3000:3000
